### ISSUE TITLE
`impersonated_user_id` misspelled?

### ISSUE THREAD

**Issue by Guara92** [PropelAuth/rust#26]
Hi,

Reading the [User Impersonation doc](https://docs.propelauth.com/overview/user-impersonation#using-user-impersonation) on your website the field indicating the user acting on behalf of the end user should be `impersonator_user_id`  instead of `impersonated_user_id`, in fact the the verb form used in the rust lib make me think that the field contains the id of the end user who was impersonated.

**Comment by andrew-propelauth** [comment]
Hey @Guara92 thanks for flagging! We just merged a fix for that, should be live in the latest release (v0.9.0)
