### ISSUE TITLE
Enhanced `User` object in middlewares: provide full `UserMetadata` and remove `metadata` field

### ISSUE THREAD

**Issue by Emulator000** [PropelAuth/rust#48]
### Description

In the current implementation of the Rust SDK, specifically within the provided crates for `axum` and `actix` middlewares, the `User` object is offered through the `metadata` field as a `HashMap`.

This implementation has a few critical issues:

1. **Incomplete user data**: the current `metadata` HashMap does not include the full structured [UserMetadata](https://github.com/PropelAuth/rust/blob/main/src/models/user_metadata.rs#L19) with all necessary user information. For instance, fields like `picture_url` and other useful data are outside this field, requiring additional authenticated API calls (using the injected PropelAuth client service) to fetch the complete information. This results in unnecessary overhead and performance inefficiencies;

2. **Potential unlimited `metadata` field**: as it stands, the `metadata` field could potentially store an infinite amount of data since it is a `HashMap` without any imposed size limits. This presents the risk of storing gigabytes of data, which can lead to excessive memory usage and potential abuse on your cloud systems.

#### Suggested solution

- **Provide full `UserMetadata`**: adjust the middleware to make the complete `UserMetadata` object accessible, containing all fields except the `metadata` field. This will reduce the need for redundant API calls to fetch user information, improving efficiency and performance;

- **Limit `metadata` field usage**: implement checks and safeguards to limit or restrict the size and amount of data stored within the `metadata` field to prevent potential abuse and excessive data storage.

#### Related issues and PRs

Additionally, a recent PR (https://github.com/PropelAuth/rust/pull/25) was created by a colleague to add support for `tonic` middleware which wasn't previously available. The improvements and considerations mentioned here should also be extended to that implementation to maintain consistency.

#### Conclusion

Enhancing the middleware to provide the full `UserMetadata` object and imposing limits on the `metadata` field will significantly enhance the SDK's efficiency and security.

These improvements will reduce unnecessary API calls, alleviate performance overheads, and mitigate potential risks related to unlimited data storage.

Thank you for your attention to this matter and your continued support of the open-source community.

**Comment by andrew-propelauth** [comment]
Thanks for writing in! For 1) you should be able to use the `properties` field. It'll include any [user properties](https://docs.propelauth.com/overview/user-management/user-properties#custom-user-properties) that you added in the dashboard (including the metadata JSON field and the picture URL).

For 2) that's something that's prevented at the API level where the request will be rejected for being too large. We haven't seen this happen too often, but if we see more of it, we'll definitely consider adding some checks to the library.
